Mkapostolov/exptra android permissions always set
telerik/Platform-Knowledge-Base pull request #83
Opened 2017-04-20 15:09 UTC by mkapostolov

2017-04-24 12:01 UTC, ggarabedian requested changes

2017-04-24 12:01 UTC, ggarabedian commented on troubleshooting/extra-android-permissions-always-set.md
> +title: Extra Android permissions always set
Title capitalization and eventually change **set** with **enabled**
For example: **Extra Android Permissions Always Enabled**

2017-04-24 12:01 UTC, ggarabedian commented on troubleshooting/extra-android-permissions-always-set.md
> +page_title: Unwanted permissions on Android build
Title capitalization and eventually change the title to:
**Unexpected Permissions in Android Аpp**

2017-04-24 12:01 UTC, ggarabedian commented on troubleshooting/extra-android-permissions-always-set.md
> +description: The APK built by the cloud service has more required permissions than I set in my project settings.
I would go for something like this. Personal preference, so feel free to keep yours.
**The built application package (APK) requires more permissions than the specified in my project settings.**

2017-04-24 12:01 UTC, ggarabedian commented on troubleshooting/extra-android-permissions-always-set.md
> +When I build my application the app asks for permissions that I didn’t set up. Permissions are added although not included in any way in the `config.xml` or the `AndroidManifest.xml`.
Build is a bit out of place here. I would go for something like this:
**When I install my application on a device, it asks for...**

2017-04-24 12:01 UTC, ggarabedian commented on troubleshooting/extra-android-permissions-always-set.md
> +    - On the left side, click on the **switch** to disable the plugin.
Somehow I do not believe that this KB should contain information on how to remove plugins. Perhaps you can add a link to the docs with info on how to manage [Core plugins](http://docs.telerik.com/platform/appbuilder/cordova/using-plugins/using-core-plugins/enable-disable-core) and remove this part.

2017-04-24 12:02 UTC, ggarabedian approved these changes

2017-04-25 06:48 UTC, mkapostolov commented on troubleshooting/extra-android-permissions-always-set.md
> +title: Extra Android permissions always set
Agree. Changed

2017-04-25 06:48 UTC, mkapostolov commented on troubleshooting/extra-android-permissions-always-set.md
> +description: The APK built by the cloud service has more required permissions than I set in my project settings.
Agree. Changed

2017-04-25 06:49 UTC, mkapostolov commented on troubleshooting/extra-android-permissions-always-set.md
> +page_title: Unwanted permissions on Android build
Agree. Changed

2017-04-25 06:49 UTC, mkapostolov commented on troubleshooting/extra-android-permissions-always-set.md
> +When I build my application the app asks for permissions that I didn’t set up. Permissions are added although not included in any way in the `config.xml` or the `AndroidManifest.xml`.
Agree. Changed

2017-04-25 06:57 UTC, mkapostolov commented on troubleshooting/extra-android-permissions-always-set.md
> +    - On the left side, click on the **switch** to disable the plugin.
Changed

2017-04-26 12:49 UTC, AntonDobrev commented
💯

2017-04-26 13:18 UTC, merged